@startuml
class CredentialService {
    - <<const>> GENERATED_PASSWORD_LENGTH : int = 32
    - <<const>> PASSWORD_CHARACTER_SET : string = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@&$?!#*^+-."
    + CredentialService(dbService:IDatabaseService, cryptoService:ICryptoService)
    + AddCredential(encryptionKey:byte[]) : void
    + ViewAllCredentials(encryptionKey:byte[]) : void
    + UpdateCredential(encryptionKey:byte[]) : void
    + DeleteCredential() : void
    + SearchCredentials(encryptionKey:byte[]) : void
    + {static} GenerateRandomPassword() : void
    - DecryptCredentialList(results:List<Dictionary<string, object>>, encryptionKey:byte[]) : List<CredentialEntry>
    - {static} CopyPasswordToClipboard(password:string) : void
    - CredentialExists(entryId:long) : bool
    - GetNextAvailableId() : long
}
ICredentialService <|-- CredentialService
CredentialService --> "_dbService" IDatabaseService
CredentialService --> "_cryptoService" ICryptoService
@enduml
