@startuml
class CredentialEntry <<sealed>> {
    + Id : long <<get>> <<init>>
    + <<required>> Platform : string <<get>> <<init>>
    + <<required>> Username : string <<get>> <<init>>
    + <<required>> Password : string <<get>> <<init>>
}
@enduml
