@startuml
interface ICredentialService {
    AddCredential(encryptionKey:byte[]) : void
    ViewAllCredentials(encryptionKey:byte[]) : void
    UpdateCredential(encryptionKey:byte[]) : void
    DeleteCredential() : void
    SearchCredentials(encryptionKey:byte[]) : void
}
@enduml
